apiVersion: v2
name: dataflow-operator
description: A Helm chart for DataFlow Operator - Kubernetes оператор для потоковой передачи данных
type: application
version: 1.0.6
appVersion: "1.0.9"
keywords:
  - dataflow
  - operator
  - kubernetes
  - streaming
home: https://github.com/dataflow-operator/dataflow
sources:
  - https://github.com/dataflow-operator/dataflow
maintainers:
  - name: ilyario (Ilya Ponomarev)
