{{- if and .Values.gui.enabled .Values.gui.serviceAccount.create (not .Values.gui.serviceAccount.name) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dataflow-operator.gui.serviceAccountName" . }}
  labels:
    {{- include "dataflow-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: gui
{{- end }}
