{{- if and .Values.monitoring .Values.monitoring.prometheusRule .Values.monitoring.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "dataflow-operator.fullname" . }}
  labels:
    {{- include "dataflow-operator.labels" . | nindent 4 }}
    {{- with .Values.monitoring.prometheusRule.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- include "dataflow-operator.prometheusRuleGroups" . | nindent 2 }}
{{- end }}
